<a href="https://colab.research.google.com/github/ColesonWelles/SudokuSolver/blob/main/My_Sudoku_Solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Attribution: https://youtu.be/G_UYXzGuqvM
'''

In [ ]:
import numpy as np
def input_grid():
  grid = []
  print("Enter each line without spaces, using 0 for unknown values")
  for i in range(1,10):
    print(f"Enter line {i}: ", end="")
    line = list(input())
    for number in range(0, len(line)):
      line[number] = int(line[number])
    grid.append(line)
  return grid

grid = input_grid()

Enter each line without spaces, using 0 for unknown values
Enter line 1: 080060001
Enter line 2: 007001000
Enter line 3: 600409087
Enter line 4: 000000940
Enter line 5: 045000008
Enter line 6: 000000500
Enter line 7: 300000090
Enter line 8: 420000000
Enter line 9: 001200700


In [ ]:
def possible(y,x,n):
  global grid
  for i in range(0,9):
    if grid[y][i] == n:
      return False
  for i in range(0,9):
    if grid[i][x] == n:
      return False
  x0 = (x//3)*3
  y0 = (y//3)*3
  for i in range (0,3):
    for j in range(0,3):
      if grid[y0+i][x0+j] == n:
        return False
  return True

In [ ]:
def solve():
  global grid
  for y in range (9): 
    for x in range(9):
      if grid[y][x] == 0:
        for n in range(1,10):
          if possible(y,x,n):
            grid[y][x] = n 
            solve()
            grid[y][x] = 0
        return 
  print(np.matrix(grid))
  input('Additional Solutions?')

In [ ]:
solve()

[[9 8 4 7 6 2 3 5 1]
 [2 5 7 3 8 1 4 6 9]
 [6 1 3 4 5 9 2 8 7]
 [8 3 2 5 1 7 9 4 6]
 [7 4 5 9 3 6 1 2 8]
 [1 9 6 8 2 4 5 7 3]
 [3 7 8 1 4 5 6 9 2]
 [4 2 9 6 7 3 8 1 5]
 [5 6 1 2 9 8 7 3 4]]
Additional Solutions?
